tests: Fix race condition in test_info_rdf
Due to the way we copy the file to have RDF/Trig extracted, it
is not an atomic operation and data may have leftovers from the
intermediate state that make the test eventually not pass due
to the unexpected data, resulting in errors like:

    not ok 10 test_info_rdf (__main__.TestCli.test_info_rdf)
     Traceback (most recent call last):
       File "/usr/lib/python3.13/unittest/case.py", line 58, in testPartExecutor
         yield
       File "/usr/lib/python3.13/unittest/case.py", line 651, in run
         self._callTestMethod(testMethod)
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
       File "/usr/lib/python3.13/unittest/case.py", line 606, in _callTestMethod
         if method() is not None:
            ~~~~~~^^
       File "/builds/carlosg/localsearch/tests/functional-tests/test_cli_info.py", line 244, in test_info_rdf
         self.validate_trig(output)
         ~~~~~~~~~~~~~~~~~~^^^^^^^^
       File "/builds/carlosg/localsearch/tests/functional-tests/test_cli_info.py", line 64, in validate_trig
         self.assertTrue(batch.execute(cancellable))
                         ~~~~~~~~~~~~~^^^^^^^^^^^^^
    gi.repository.GLib.GError: tracker-db-interface-error-quark: nie:byteSize: Unable to insert multiple values on single valued property (old: 34, new: 0) (0)

These leftovers after updates are something for TinySparql to fix, but
the purpose of this test is far more superficial, just ensuring that
"localsearch info --output-format ..." works as expected. Make this
test create a file atomically instead of incrementally copying it, so
that the data is ensured to be reliable.