trackertestutils: Implement missing exception
This exception is used by the code handling D-Bus daemons and
services, but not defined in this scope. This resulted in a pretty:

NameError: name 'AwaitTimeoutException' is not defined

When a D-Bus timeout would be hit.